server:
  port: 8018
debug: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
     enabled: true
spring:
  application:
    name: system-web
  boot:
    admin:
      client:
        url: http://localhost:8788
management:
  endpoints:
    web:
      exposure:
        include: '*'